### PR TITLE
Fix File Loading

### PR DESCRIPTION
**Pull request by Saifallak**
Fix File Loading

when loading duration its always load from url instead of file

also added Duration 60 sec as fallback so it doesnt crash

also i have question, why file is future of file? instead of path/File

### CODE REVIEW

**Comment by Saifallak** [comment]
if you need to use this fork

```yaml
  voice_message_package:
    git:
      url: https://github.com/AQuadic/voice_message_player.git
```

**Comment by gbbest15** [comment]
can you update the gradle

**Comment by Saifallak** [comment]
> can you update the gradle

I don't use it anymore, so fork and update it yourself, thank you

**Comment by Saifallak** [comment]
@mehranshoqi thank you for merging this

**Pull request merged**
